name: bicep
on:
  push:
    branches:
      - main
env:
  RESOURCE_TYPE: 'fnc'
  ENVIRONMENT: 'dev'
  INSTANCE: '1'

permissions:
      id-token: write
      contents: read

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        ref: main

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}          
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}    
          
    - name: 'Run Azure CLI commands'
      
      run: |
        westeurope=westeurope$RESOURCE_TYPE$ENVIRONMENT$INSTANCE
        az bicep build --stdout --file './iac/main.bicep'
        az deployment sub validate --name $westeurope --location 'westeurope' --template-file './iac/main.bicep' --parameters resourcetype=$RESOURCE_TYPE environment=$ENVIRONMENT region='we' instance=$INSTANCE tags=@./iac/tags.json
        az deployment sub create --what-if --name $westeurope --location 'westeurope' --template-file './iac/main.bicep' --parameters resourcetype=$RESOURCE_TYPE environment=$ENVIRONMENT region='we' instance=$INSTANCE tags=@./iac/tags.json
        az deployment sub create --name $westeurope --location 'westeurope' --template-file './iac/main.bicep' --parameters resourcetype=$RESOURCE_TYPE environment=$ENVIRONMENT region='we' instance=$INSTANCE tags=@./iac/tags.json
