name: bicep
on:
  push:
    branches:
      - main
env:
  sku: 'S1'
  RESOURCE_TYPE: 'asp'
  ENVIRONMENT: 'dev'
  INSTANCE1: '1'
  INSTANCE2: '2'


permissions:
      id-token: write
      contents: read

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        ref: main

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}          
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}    
          
    - name: 'Run Azure CLI commands'
      
      run: |
        westeurope=westeurope$RESOURCE_TYPE$ENVIRONMENT$INSTANCE1
        westeurope=westeurope$RESOURCE_TYPE$ENVIRONMENT$INSTANCE2
        az bicep build --stdout --file './iac-appServicePlan/main.bicep'
        az deployment sub validate --name $westeurope --location 'westeurope' --template-file './iac-appServicePlan/main.bicep' --parameters resourcetype=$RESOURCE_TYPE environment=$ENVIRONMENT region='we' instance1=$INSTANCE1 instance2=$INSTANCE2 sku=$sku tags=@./iac-appServicePlan/tags.json
        az deployment sub create --what-if --name $westeurope --location 'westeurope' --template-file './iac-appServicePlan/main.bicep' --parameters resourcetype=$RESOURCE_TYPE environment=$ENVIRONMENT region='we' instance1=$INSTANCE1 instance2=$INSTANCE2 sku=$sku tags=@./iac-appServicePlan/tags.json
        az deployment sub create --name $westeurope --location 'westeurope' --template-file './iac-appServicePlan/main.bicep' --parameters resourcetype=$RESOURCE_TYPE environment=$ENVIRONMENT region='we' instance=$INSTANCE instance2=$INSTANCE2 sku=$sku tags=@./iac-appServicePlan/tags.json